# Generated by Django 6.0.7 on 2026-08-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empresa_alter_perfil_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_dono',
            field=models.BooleanField(default=False, help_text='Indica se este perfil representa o dono da empresa.'),
        ),
    ]
