# Generated by Django 6.0.5 on 2026-08-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='preco_unitario',
        ),
    ]
