# Generated by Django 6.0.7 on 2026-08-09 03:08

from django.conf import settings
from django.db import migrations, models


def preencher_numero_vendas(apps, schema_editor):
    Venda = apps.get_model('vendas', 'Venda')
    vendas = Venda.objects.order_by('usuario_id', 'id')
    contadores = {}
    for venda in vendas:
        usuario_id = venda.usuario_id
        contadores[usuario_id] = contadores.get(usuario_id, 0) + 1
        venda.numero = contadores[usuario_id]
        venda.save(update_fields=['numero'])


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_venda_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_venda']},
        ),
        migrations.AddField(
            model_name='venda',
            name='numero',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(preencher_numero_vendas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.UniqueConstraint(fields=('usuario', 'numero'), name='unique_venda_numero_por_usuario'),
        ),
    ]
